### ISSUE TITLE
Latest link does not exist

### ISSUE THREAD

**Issue by bkmgit** [ruby-gnome/ruby-gnome.github.io#5]
Link to https://ruby-gnome.github.io/ruby-gnome/doc/latest/ is broken. The folder does not exist. This link should be removed. Possibly https://ruby-gnome.github.io/ruby-gnome/doc/dev/ should have information which indicates that the documentation may not be in sync with the existing code, and that pull requests are welcome.

**Comment by rubyFeedback** [comment]
Does it work now?

I see some API entries at:

https://ruby-gnome.github.io/ruby-gnome/doc/dev/

I am a bit confused whether this is all. If I remember correctly there was a lot more ruby-gtk2
specific documentation on the old wiki, but my memory is a bit fuzzy there.

**Comment by kou** [comment]
https://ruby-gnome.github.io/ruby-gnome/doc/latest/ will be available once we release new version.

https://ruby-gnome.github.io/ruby-gnome/doc/dev/ doesn't include gtk2 gem's document because we dropped support for it.

If you want, you can find raw data at https://github.com/ruby-gnome/doc/tree/master/hiki/data/en/text .

**Comment by kou** [comment]
https://ruby-gnome.github.io/ruby-gnome/doc/latest/  is available now because I've release 4.0.0 (and 4.0.1).

https://ruby-gnome.github.io/ruby-gnome/doc/4.0.0/ and https://ruby-gnome.github.io/ruby-gnome/doc/4.0.1/ are also available.
